<?php
// +----------------------------------------------------------------------
// | Created by PhpStorm.
// +----------------------------------------------------------------------
// | user : 放下
// +----------------------------------------------------------------------
// | blog : www.putyy.com
// +----------------------------------------------------------------------
// | email: 10945014@qq.com
// +----------------------------------------------------------------------
// | Date : 2019/8/1 10:40
// +----------------------------------------------------------------------


namespace WGCYunPay\Service;

use WGCYunPay\AbstractInterfaceTrait\BaseService;
use WGCYunPay\Data\Router;

class RiskCheckService extends BaseService
{
    /**
     * 身份证号 护照、港澳台居⺠居住证等 必填
     * @var
     */
    private $idCard;

    /**
     * 姓名 必填
     * @var
     */
    private $realName;

    /**
     * 打款⾦额 必填
     * @var
     */
    private $amount;

    public function setInfo($idCard, $realName, $amount)
    {
        $this->idCard = $idCard;
        $this->realName = $realName;
        $this->amount = $amount;
        return $this;
    }


    protected function getDes3Data()
    {
        // TODO: Change the autogenerated stub
        return ['id_card'=>$this->idCard, 'real_name'=>$this->realName, 'broker_id'=>$this->config->broker_id, 'amount'=>$this->amount];
    }

    protected function getRequestInfo()
    {
        return [Router::RISK_CHECK_AMOUNT];
    }
}
